---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sock-shop-deny-all
  namespace: sock-shop
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-front-end
  namespace: sock-shop
spec:
  podSelector:
    matchLabels:
      component: front-end
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8079
  egress:
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 80
    - to:
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-databases
  namespace: sock-shop
spec:
  podSelector:
    matchExpressions:
      - key: component
        operator: In
        values:
          - catalogue-db
          - carts-db
          - orders-db
          - user-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-rabbitmq
  namespace: sock-shop
spec:
  podSelector:
    matchLabels:
      component: rabbitmq
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 5672
        - protocol: TCP
          port: 15672
