---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sock-shop
data:
  node-env: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: sock-shop
type: Opaque
stringData:
  mysql-root-password: "super_secure_fake_password_123"
