---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: sock-shop
  labels:
    app: sock-shop
    component: front-end
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8079
  selector:
    component: front-end
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: sock-shop
  labels:
    app: sock-shop
    component: catalogue
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    component: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
  namespace: sock-shop
  labels:
    app: sock-shop
    component: catalogue-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    component: catalogue-db
