apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: astronomy-shop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Source 1: Upstream Helm chart repository
    - repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
      chart: opentelemetry-demo
      targetRevision: 0.40.9
      helm:
        valueFiles:
          - $values/platform/helm/values.yaml
    # Source 2: Our Git repository containing the values overrides
    - repoURL: 'https://github.com/letsconfuse/shop-devops.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: astronomy-shop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
